# Generated by Django 4.2.7 on 2023-11-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_pessoa_fisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_cliente', models.CharField(max_length=255)),
                ('nr_cpf', models.CharField(max_length=15)),
            ],
        ),
    ]
