# Generated by Django 4.2.7 on 2023-11-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sample_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_pessoa_fisica',
            name='nr_cpf',
            field=models.CharField(max_length=14),
        ),
    ]
